### ISSUE TITLE
[Question]: How is this compared to SM-11?

### ISSUE THREAD

**Issue by anasouardini** [open-spaced-repetition/ts-fsrs#136]
I'm just interested to see if the CPU-intensive SM-11 worth it when this is available, sorry if my question is dumb.

**Comment by L-M-Sherlock** [comment]
I don't know how to implement SM-11. At least FSRS is better than SM-16: https://github.com/open-spaced-repetition/fsrs-vs-sm17

**Comment by anasouardini** [comment]
Thank you, I got my answer.
