### ISSUE TITLE
[Question]: When to use long_term_scheduling

### ISSUE THREAD

**Issue by powderham** [open-spaced-repetition/ts-fsrs#140]
I was wondering under what conditions you'd set `enable_short_term` as true?

My first understanding was this would be a business logic decision, _do i want users to review things quickly_?

however after a few weeks using the package i'm wondering if it's more to do with the cards stability?
In which case, I wont pass a global `FSRS` object around, but instead instantiate it per card.

I'll happily add to the docs to clarify with the answer

**Comment by ishiko732** [comment]
> I was wondering under what conditions you'd set `enable_short_term` as true?
> however after a few weeks using the package i'm wondering if it's more to do with the cards stability?

Before ts-fsrs v4.0.0, the scheduler defaulted to `enable_short_term=true`. In this case, the card's state could transition through `State.New` -> `State.Learning` or `State.Review` -> `State.Relearning`. When `enable_short_term=true`, the stability changes of multiple reviews on the same day are taken into account, and `next_short_term_stability` is called to calculate the next stability. When `enable_short_term=false`, `next_short_term_stability` is not called, and `State.(Re)Learning` will not occur.


> My first understanding was this would be a business logic decision, _do i want users to review things quickly_?

User's quick review is one aspect, but based on my usage, I should be using the Long-Scheduler for materials that have already been learned in the real world. I'm not quite sure about the specific application scenarios, sorry about that :) 
You can ask @L-M-Sherlock 



> In which case, I wont pass a global `FSRS` object around, but instead instantiate it per card.

No problem

**Comment by L-M-Sherlock** [comment]
The short-term memory is hard to predict, and there isn't any optimal short-term scheduling. I designed the short-term scheduler because I'm an Anki user. It's mostly about dealing with users habits.
