### ISSUE TITLE
Question: Why does the function give every possible card based on every possible grade?

### ISSUE THREAD

**Issue by Brentably** [open-spaced-repetition/ts-fsrs#70]
Maybe there's something I'm not understanding... why does the f.repeat() function take the card / date as an argument and return every possible card based on every possible grade as a result?

Why doesn't it take a grade as an argument and return just a single new card as a result?

Not a huge deal, but am worried there's something I'm missing.

**Comment by L-M-Sherlock** [comment]
Many users want to preview the intervals of all grades before they press the grading button.

**Comment by ishiko732** [comment]
I think you can take a look at https://github.com/open-spaced-repetition/py-fsrs/issues/21, as it has relevant descriptions.

You can customize the implementation of the `afterHandler` to return the corresponding card data based on the Grade.

ts-fsrs-demo Example:
https://github.com/ishiko732/ts-fsrs-demo/blob/8e17c5a858abfbd1c5da7ae56de932fc0126a380/src/lib/card.ts#L42-L68
https://github.com/ishiko732/ts-fsrs-demo/blob/8e17c5a858abfbd1c5da7ae56de932fc0126a380/src/lib/card.ts#L103
