### ISSUE TITLE
发布到openharmony三方库中心仓库

### ISSUE THREAD

**Issue by RainVice** [open-spaced-repetition/ts-fsrs#78]
你好，我将ts-fsrs修改以适配OpenHarmonyOS系统的ArkTS语言，现在发布到了[OpenHarmony三方库中心仓](https://ohpm.openharmony.cn/#/cn/detail/@rv%2Fts-fsrs)，之前忘记在这里询问意见，如果您不同意的话，我马上将OpenHarmony三方库中心仓中的依赖下架

**Comment by L-M-Sherlock** [comment]
<img width="1341" alt="image" src="https://github.com/open-spaced-repetition/ts-fsrs/assets/32575846/b9060b2b-25a6-4d8b-85a4-c0c2c27216ae">

我不理解为什么这两个对不上

**Comment by RainVice** [comment]
> <img alt="图像" width="1341" src="https://private-user-images.githubusercontent.com/32575846/318619167-b9060b2b-25a6-4d8b-85a4-c0c2c27216ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjUwOTEsIm5iZiI6MTcxMjAyNDc5MSwicGF0aCI6Ii8zMjU3NTg0Ni8zMTg2MTkxNjctYjkwNjBiMmItMjVhNi00ZDhiLTg1YTQtYzBjMmMyNzIxNmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyMjYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODVlNTIxYTE3NTY3YTg1OGQ0ZThiNzQ0ZDkyNmJjNjZjMjhmYjdiOTEwNTI2OTM2N2EyODZkZTI3NTg3NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CS1RXNebiRsPdwj5AKUm5p-0VApUr8Vlnnseffypl1U">
> 我不理解为什么这两个对不上。如果这个包和 ts-fsrs 本身有区别，建议改名。

这个是因为刚开始修改时没有考虑过上传到仓库的事，其中的代码都是按照ts-fsrs修改的，只是修改了一些ArsTS不支持的语法，你的建议是修改仓库名？还是修改
![image](https://github.com/open-spaced-repetition/ts-fsrs/assets/71380096/0d3414f2-7f85-401b-b00c-712f86e5718b)
这里的地址为本仓库

**Comment by L-M-Sherlock** [comment]
我的建议是改名，不过主要开发者是 @ishiko732，请等待他的回复。

**Comment by ishiko732** [comment]
建议改名哦，https://github.com/RainVice/fsrs 注明参考本仓库实现即可，不然到时候开发者有issues不知道往哪个仓库提...

我这边是没有计划适配HarmonyOS的。

**Comment by RainVice** [comment]
> 建议改名哦，https://github.com/RainVice/fsrs 注明参考本仓库实现即可，不然到时候开发者有issues不知道往哪个仓库提...
> 
> 我这边是没有计划适配HarmonyOS的。

好的
