### ISSUE TITLE
Questions about using cards

### ISSUE THREAD

**Issue by hvven** [open-spaced-repetition/ts-fsrs#79]
First of all huge thanks for making this. I want to ramble about how grateful I am for this library but I’ll just go straight to asking the questions.

I saw the `ts-fsrs-demo` but I have a really hard time reading code (actually just reading in general) and I tried my best to understand it but I’m still confused about stuff.

1.
If I grade a newly created card “Again” it’s due in 1 minute, is there a way to lower that? For examples to 30 seconds? Because I can’t recall it at all after a minute because I’m actually very dumb.

2.
When am I expected to `f.repeat(card, now)` the current card, and how do I set the preview times (those things that say 1min, 5min, 1day, 3day)?

I looked into this and I’m currently using `f.repeat` and getting the next card at the same time when the user presses one of the 4 grade buttons. And I’m setting the preview times before I actually grade the current card by using `f.repeat` the current card but not setting the card with the results. Am I doing everything correctly?

3.
How do I get a card like anki in a list of cards? Do I get the one with the lowest due date sorted by Review -> Relearning, Learning -> New?

4.
Do I have to store `const f = new FSRS()` on localStorage with the cards? Does it store any information about the cards? Or do I only have to store the cards?

**Comment by ishiko732** [comment]
> If I grade a newly created card “Again” it’s due in 1 minute, is there a way to lower that? For examples to 30 seconds? Because I can’t recall it at all after a minute because I’m actually very dumb.

Yes, you can change it to 30 seconds to see the card again by utilizing the afterHandler. For example, in my implementation at https://github.com/ishiko732/ts-fsrs-demo/blob/cabdc6a1eed70e9159bd7f859e67d29e61a1087d/src/vendor/fsrsToPrisma/handler.ts#L51-L75, I implemented a card suspension feature. 

Additionally, no one is truly dumb, so please have confidence in yourself!

```diff
export function repeatAfterHandler(lapses: number, recordLog: RecordLog) {
  const record: RecordLogPrisma = {} as RecordLogPrisma;
+  const againDue = new Date(
+    recordLog[Rating.Again].card.last_review!.getTime() + 30 * 1000
+  );
  for (const grade of Grades) {
    // lapses use userParams.lapses
    const suspended =
      grade === Rating.Again &&
      recordLog[grade].card.lapses > 0 &&
      recordLog[grade].card.lapses % lapses == 0;

+    const due = grade === Rating.Again ? againDue : recordLog[grade].card.due;
    record[grade] = {
      card: {
        ...(recordLog[grade].card as Card & { cid: number; nid: number }),
+        due: due,
        state: State[recordLog[grade].card.state] as PrismaState,
        last_review: recordLog[grade].card.last_review ?? null,
        suspended: suspended,
      },
      log: {
        ...(recordLog[grade].log as unknown as RevlogPrismaUnChecked),
        state: State[recordLog[grade].log.state] as PrismaState,
        rating: Rating[recordLog[grade].log.rating] as PrismaRating,
      },
    };
  }
  return record;
}
```

**Comment by ishiko732** [comment]
> When am I expected to `f.repeat(card, now)` the current card, and how do I set the preview times (those things that say 1min, 5min, 1day, 3day)?

You may need to implement a three-box structure similar to ts-fsrs-demo, or you can refer to https://www.juliensobczak.com/inspect/2022/05/30/anki-srs.html for guidance. You can determine whether to show a card based on whether the due time is less than or equal to the current time of the day. As for setting the preview times (1min, 5min, 1day, 3day), you can define those intervals based on your requirements and adjust the scheduling logic accordingly.

![fsrs-TS-FSRS-BOXES drawio](https://github.com/open-spaced-repetition/ts-fsrs/assets/62931549/6d151abc-8296-4f69-8685-6e2a0bd59d0f)

**Comment by ishiko732** [comment]
> I looked into this and I’m currently using `f.repeat` and getting the next card at the same time when the user presses one of the 4 grade buttons. And I’m setting the preview times before I actually grade the current card by using `f.repeat` the current card but not setting the card with the results. Am I doing everything correctly?

Your approach is correct. In `ts-fsrs-demo`, they use the server-side implementation of `f.repeat` because they designed it to not trust client-side data. However, you can also use `f.repeat` on the client-side and trust the result of f.repeat to directly store the data.

**Comment by ishiko732** [comment]
> Do I have to store `const f = new FSRS()` on localStorage with the cards?

You can't directly store the FSRS instance itself. Instead, you should store the FSRSParameters and Cards. Storing them in localStorage is possible, but you need to consider the size limitations of localStorage.I suggest storing the data in a database, such as SQLite or MySQL...

![fsrs-ER-1 drawio](https://github.com/open-spaced-repetition/ts-fsrs/assets/62931549/c722f062-1bde-400e-ab92-258bea354d80)

**Comment by ishiko732** [comment]
> Does it store any information about the cards? Or do I only have to store the cards?

It is recommended to store all card information. If you don't need to perform optimization, you may not need the `revlog`.

**Comment by hvven** [comment]
I’m extremely thankful for the answer. And again thanks a lot for making the library too. I don’t have any questions now, thank you.
