### ISSUE TITLE
[Feat] switch of enable/disable short-term schedule

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/ts-fsrs#98]
The current implementation imitates the learning step mechanism of Anki, which forces users to do more reviews when they learn a new card or forget a stale card. I'm considering to add a switch to enable/disable it. In disable mode, a new card will enter into long-term review after the first rating, just like users who leave learning steps empty in Anki. Likewise, if the user press `again` in a stale card, it won't enter into relearning state.

**Comment by ishiko732** [comment]
> if the user press `again` in a stale card, it won't enter into relearning state.

 Will a card in `State.Review` remain in `State.Review` after the user press `Again`?

**Comment by ishiko732** [comment]
I believe it’s necessary to perform a minor refactor on current ts-fsrs project.

**Comment by L-M-Sherlock** [comment]
> Will a card in `State.Review` remain in `State.Review` after the user press `Again`?

Yes. Actually, State.Learning and State.Relearning will not exist in that mode.

**Comment by ishiko732** [comment]
> State.Learning and State.Relearning will not exist in that mode.

If the current card status is (Re)Learning, is it treated as a State.Review card when transitioning to the long-term scheduler?

https://github.com/open-spaced-repetition/ts-fsrs/blob/f838a179f9371e8acf8703a028aa04995f5cdfa3/__tests__/impl/long-term_schduler.test.ts#L211-L224

**Comment by L-M-Sherlock** [comment]
> If the current card status is (Re)Learning, is it treated as a State.Review card when transitioning to the long-term scheduler?

Yes.
